-- example
-- create table table_name(
--     text_field varchar not null,
--     small_int_field int2,
--     check_field varchar unique constraint check_field_words CHECK (check_field ~ '^[\w]+$'),
--     id bigserial primary key);